# Generated by Django 5.1.6 on 2025-02-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='check_in_qr_code',
            field=models.ImageField(blank=True, upload_to='checkin/qrcode/'),
        ),
    ]
